version: '3'

services:
  app:
    image: scalaops/scala-graalvm:scala-2.11.8-sbt-1.1.5-graalvm-1.0.0-rc1
    command: ./generate-native-image.sh
    volumes:
      - .:/app
      - ~/.ivy2:/root/.ivy2
      - ~/.sbt:/root/.sbt
      - ~/.coursier:/root/.coursier 